<nav><h3>
  <div class="container"> 
    
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="index.php">Dashboard <span class="sr-only">(current)</span></a> </li>
		<li><a href="client_details.php">Client Detials</a> </li>
        <li class="dropdown"> <a href="students.php" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">Students <span class="caret"></span></a>
          <ul class="dropdown-menu"><h4>
            <li><a href="students.php">Student List</a> </li>
            <li><a href="groups.php">Groups</a> </li></h4>
          </ul>
        <li class="active"><a href="email.php">Email <span class="sr-only">(current)</span></a> </li>        
        <li class="active"><a href="studentlogin.php">Student Login <span class="sr-only">(current)</span></a> </li>
        </li>
      </ul>
      
      
    </div>
    <!-- /.navbar-collapse --> 
  </div>
  <!-- /.container-fluid --> 
  </h3>
</nav>
